set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m55)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(PREFIX arm-none-eabi-)

if(DEFINED GCC_PATH)
    set(TOOLCHAIN_PREFIX "${GCC_PATH}/${PREFIX}")
elseif(DEFINED ENV{GCC_PATH})
    set(TOOLCHAIN_PREFIX "$ENV{GCC_PATH}/${PREFIX}")
else()
    set(TOOLCHAIN_PREFIX "${PREFIX}")
endif()

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_OBJCOPY      "${TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_SIZE         "${TOOLCHAIN_PREFIX}size")
set(CMAKE_READELF      "${TOOLCHAIN_PREFIX}readelf")
